import Link from 'next/link';
import { ArrowRight, Blocks, Cable, FileCode2, Package2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { repoUrl } from '@/lib/shared';
const highlights = [
  { title: 'Protocol-first', description: 'Keep tools, persistence, and business logic in the host app while the model emits compact UI intent.', icon: FileCode2 },
  { title: 'Composable runtime', description: 'Use @toon-ui/core on the server and choose either @toon-ui/react or @toon-ui/toon-ui on the client.', icon: Package2 },
  { title: 'Safe interactions', description: 'Reply and submit events return structured payloads that can be re-injected into your chat loop.', icon: Cable },
  { title: 'Official catalog', description: 'Documented grammar, validation, and adapter APIs make the integration teachable and testable.', icon: Blocks }
];
export default function HomePage() { return <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-16 px-6 py-16 md:px-10"><section className="grid gap-8 md:grid-cols-[1.3fr_0.9fr] md:items-center"><div className="space-y-6"><span className="inline-flex w-fit rounded-full border px-3 py-1 text-xs font-medium text-muted-foreground">Next.js + Fumadocs + shadcn/ui</span><div className="space-y-4"><h1 className="max-w-3xl text-4xl font-semibold tracking-tight md:text-6xl">Build AI-native interfaces with markdown plus <span className="text-primary">toon-ui</span> blocks.</h1><p className="max-w-2xl text-base text-muted-foreground md:text-lg">ToonUI lets an LLM describe UI in a compact, typed language while your application keeps ownership of tools, transport, persistence, and business rules.</p></div><div className="flex flex-wrap gap-3"><Button asChild><Link href="/docs">Read the docs<ArrowRight className="size-4" /></Link></Button><Button asChild variant="outline"><Link href={repoUrl} target="_blank" rel="noreferrer">View repository</Link></Button></div></div><div className="rounded-2xl border bg-card p-6 text-sm shadow-sm"><pre className="overflow-x-auto text-xs leading-6 text-card-foreground">{`import { createToonProtocol } from '@toon-ui/core';\nimport { ToonMessage, createToonClient } from '@toon-ui/toon-ui';\n\nconst protocol = createToonProtocol();\nconst toon = createToonClient();\n\nconst system = [protocol.prompt, appInstructions].join('\\n\\n');`}</pre></div></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{highlights.map(({ title, description, icon: Icon }) => <article key={title} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-4 inline-flex rounded-lg border p-2 text-primary"><Icon className="size-4" /></div><h2 className="mb-2 font-semibold">{title}</h2><p className="text-sm text-muted-foreground">{description}</p></article>)}</section></main>; }
