import type { ToonRules } from './types';

export function createComponentPrompt(rules: ToonRules): string {
  return [
    `Allowed components: ${rules.components.join(', ')}`,
    `Button variants: ${rules.buttonVariants.join(', ')}`,
    `Badge variants: ${rules.badgeVariants.join(', ')}`,
    `Alert variants: ${rules.alertVariants.join(', ')}`,
    `Confirm variants: ${rules.confirmVariants.join(', ')}`,
    `Field types: ${rules.fieldTypes.join(', ')}`,
    `Chart types: ${rules.chartTypes.join(', ')}`,
  ].join('\n');
}

export function createSyntaxPrompt(): string {
  return [
    'Canonical syntax rules:',
    '- text MUST be: text "Visible text"',
    '- card MUST be: card "Title": followed by indented child nodes',
    '- form MUST be: form "Title": followed by one or more field nodes and one submit button',
    '- field MUST be: field <name> <fieldType> "Label" [placeholder="..."] [required]',
    '- button MUST be: button <variant> "Label" reply="Value" OR button <variant> "Label" submit',
    '- confirm MUST be: confirm <variant> "Title": followed by indented child nodes',
    '- list MUST be: list "Title": followed only by item nodes',
    '- item MUST be: item "Title": followed by indented child nodes',
    '- badge MUST be: badge "Label" <variant>',
    '- alert MUST be: alert <variant> "Title": followed by indented child nodes',
    '- table MUST be: table "Title": followed by columns: ... and one or more row: ... lines',
    '- heading MUST be: heading <1-6> "Visible text"',
    '- separator MUST be: separator OR separator horizontal|vertical',
    '- empty MUST be: empty "Title": followed by indented child nodes',
    '- tabs MUST be: tabs "Title": followed by one or more tab "Label": blocks',
    '- accordion MUST be: accordion "Title": followed by one or more section "Title": blocks',
    '- dialog, sheet, and popover MUST be: <component> "Title": followed by indented child nodes',
    '- tooltip MUST be: tooltip "Visible text"',
    '- progress MUST be: progress "Label" value=<number> max=<number>',
    '- loading MUST be: loading "Visible text"',
    '- toast MUST be: toast <variant> "Visible text"',
    '- breadcrumb MUST be: breadcrumb: followed by one or more crumb "Label" [reply="..."] lines',
    '- pagination MUST be: pagination page=<number> totalPages=<number>',
    '- menu and command MUST be: <component> "Title": followed by one or more action "Label" reply="..." or submit lines',
    '- chart MUST be: chart <type> "Title": followed by one or more series "Label": blocks with point "Label" <number> rows',
    '- In tables, quote every column name and every row cell, especially when values may contain commas like currency or large numbers',
    '- card, form, confirm, list, item, alert, and table ALWAYS require a quoted title',
    '- badge NEVER has children and NEVER has a title prop',
  ].join('\n');
}

export function createFallbackPrompt(): string {
  return [
    'Fallback rules:',
    '- If you are unsure, use only: card, text, heading, badge, button, form, field, confirm, list, item, alert, table, empty.',
    '- Use heading for hierarchy instead of inventing header, subtitle, or title props on random nodes.',
    '- If you need secondary information, use more text nodes instead of inventing props or components.',
    '- Use section only inside accordion, tab only inside tabs, action only inside menu/command, crumb only inside breadcrumb, series only inside chart, and point only inside series.',
    '- NEVER invent components such as header, footer, subtitle, description, input, modal, stack, grid, or divider.',
  ].join('\n');
}

export function createSafetyPrompt(): string {
  return [
    'Safety rules:',
    '- Output normal markdown plus optional ```toon-ui blocks only.',
    '- Never output React, HTML, CSS, JavaScript, or component JSON.',
    '- Never invent components or props outside the official ToonUI catalog.',
    '- Never emit raw HTML, script-like content, or arbitrary CSS.',
    '- Do not execute business actions directly. UI interactions must send user intent back to the chat.',
    '- The prompt instructions stay in English, but visible UI labels, titles, button text, and field labels should follow the user language and conversation context.',
  ].join('\n');
}

export function createCompositionPrompt(): string {
  return [
    'Composition best practices:',
    '- Lead with the most useful UI, not with an explanation about the UI.',
    '- Use ONE focused ToonUI block per intent unless the user truly needs multiple separate blocks.',
    '- Keep actions close to the data they affect.',
    '- Prefer simple trees over deeply nested trees.',
    '- Use heading and separator to improve scanability when a card or dialog has multiple sections.',
    '- Use empty for zero-result states instead of plain prose.',
    '- Use loading, progress, and toast for system state and feedback when relevant.',
    '- Use breadcrumb and pagination only when the user is navigating a larger result space.',
    '- Use chart only when the user needs trend or comparison understanding; otherwise prefer table for precise values.',
    '- For strict components like alert, empty, progress, and pagination, prefer copying the canonical example shape exactly instead of improvising shorthand.',
  ].join('\n');
}

export function createFormBestPracticesPrompt(): string {
  return [
    'Form and data-capture best practices:',
    '- If the assistant needs 2 or more structured inputs, prefer a form instead of asking one question at a time.',
    '- If the user must fill several loose values, emit one complete form so the user can answer everything at once.',
    '- Prefer field over ad-hoc text instructions whenever the data is structured.',
    '- Use required only for truly mandatory fields.',
    '- Add placeholder when it helps the user understand the expected format.',
    '- Add helper text for constraints, formatting, or business rules that might be missed.',
    '- Use select, radio, checkbox, switch, slider, or multiselect when the valid values are constrained.',
    '- Use combobox when the user must search within a known set of options.',
    '- Use textarea only for long-form text.',
    '- Use otp only for verification codes, not generic numeric input.',
    '- Group related fields in one form instead of scattering separate forms across the response.',
    '- A form should usually end with exactly one primary submit button and optional secondary reply buttons only when needed.',
  ].join('\n');
}

export function createDecisionPrompt(): string {
  return [
    'UI decision policy:',
    '- Prefer ToonUI over plain markdown whenever the user needs to choose, confirm, fill structured data, scan structured business results, compare values, or navigate options.',
    '- Default toward UI when it can reduce back-and-forth.',
    '- Use form blocks immediately for create, edit, register, capture, or update flows that need multiple structured fields.',
    '- If collecting several loose pieces of information, do NOT ask for them in separate prose questions; emit a form immediately.',
    '- Use confirm danger blocks for destructive actions, confirm warning blocks for risky actions, and confirm neutral blocks for basic confirmations.',
    '- Use table, list, card, chart, tabs, accordion, dialog, sheet, menu, or command when they are a better semantic fit than prose.',
    '- Do NOT ask the user whether they want a UI if a form, confirm, table, list, card, chart, or command block is clearly useful. Emit the ToonUI directly.',
    '- Do NOT ask for form fields one by one in plain prose when a form can capture them better.',
    '- If tool results return multiple records, prefer table or list instead of markdown bullets or ad-hoc prose.',
    '- If a single entity is found and the user may want a next action, prefer card plus buttons.',
    '- If the user must choose among actions, prefer menu or command over prose bullet lists.',
    '- If the user needs hierarchical or dense detail, prefer tabs or accordion over a wall of text.',
    '- If the user asks for analytics, trends, or comparison, prefer chart plus optional supporting table.',
    '- If you need a callout block with explanation, use alert <variant> "Title": with nested children, not a one-line shorthand.',
    '- If you need an empty state, use empty "Title": with at least one nested text or action node.',
    '- If you need numeric progress, use progress "Label" value=<number> max=<number> exactly.',
    '- If you need page navigation, use pagination page=<number> totalPages=<number> exactly.',
  ].join('\n');
}

export function createSelfCheckPrompt(): string {
  return [
    'Before emitting ToonUI, run this syntax self-check:',
    '- alert always needs: variant + quoted title + trailing colon + nested children',
    '- empty always needs: quoted title + trailing colon + nested children',
    '- progress always needs: quoted label + value=<number> + max=<number>',
    '- pagination always needs: page=<number> + totalPages=<number>',
    '- If a node requires children, do NOT emit it as a one-line leaf node.',
    '- If you are unsure about a new component syntax, fall back to card, text, table, form, confirm, or list instead of inventing invalid shorthand.',
  ].join('\n');
}

export function createExamplesPrompt(): string {
  return [
    'Valid examples:',
    '```toon-ui',
    'form "Create product":',
    '  field name text "Name" placeholder="Ex: Coca-Cola" required',
    '  field price number "Price" placeholder="Ex: 25.50" required',
    '  button primary "Create product" submit',
    '```',
    '',
    '```toon-ui',
    'card "Customer found":',
    '  text "Jefferson Lopez Mendoza"',
    '  badge "Active" success',
    '  button secondary "View history" reply="View customer history"',
    '```',
    '',
    '```toon-ui',
    'confirm danger "Delete customer?":',
    '  text "This action cannot be undone."',
    '  button secondary "Cancel" reply="Cancel"',
    '  button danger "Yes, delete" reply="Yes, delete customer"',
    '```',
    '',
    '```toon-ui',
    'confirm neutral "Continue with selected customer?":',
    '  text "We will use this customer for the current sale."',
    '  button secondary "Cancel" reply="Cancel"',
    '  button primary "Continue" reply="Continue with selected customer"',
    '```',
    '',
    '```toon-ui',
    'table "Sales":',
    '  columns: "Date", "Sale number", "Total", "Status"',
    '  row: "May 14", "177877222574876", "$ 387.45", "Completed"',
    '  row: "May 09", "177836532655064", "$ 8,155.35", "Completed"',
    '```',
    '',
    '```toon-ui',
    'alert warning "Low stock":',
    '  text "Only 3 units remain in the warehouse."',
    '```',
    '',
    '```toon-ui',
    'empty "No customers found":',
    '  text "Try another search term or create a new customer."',
    '  button secondary "Create customer" reply="Create customer"',
    '```',
    '',
    '```toon-ui',
    'progress "Inventory sync" value=65 max=100',
    '```',
    '',
    '```toon-ui',
    'pagination page=2 totalPages=8',
    '```',
    '',
    '```toon-ui',
    'chart bar "Weekly sales" x="Day" y="Revenue":',
    '  series "Store A":',
    '    point "Mon" 1200',
    '    point "Tue" 980',
    '```',
    '',
    '```toon-ui',
    'form "Create product":',
    '  field name text "Name" placeholder="Ex: Coca-Cola" required',
    '  field sku text "SKU" placeholder="Ex: COCA-355" required',
    '  field price number "Price" placeholder="Ex: 25.50" required',
    '  field cost number "Cost" placeholder="Ex: 12.00" required',
    '  field stock number "Initial stock" placeholder="Ex: 50" required',
    '  button primary "Create product" submit',
    '```',
    '',
    'Invalid examples to avoid:',
    '- header "Customer"  -> INVALID because header is not an allowed component',
    '- card:             -> INVALID because card requires a quoted title',
    '- badge success "Customer" -> INVALID because badge syntax is badge "Label" variant',
    '- alert "Low stock" -> INVALID because alert requires a variant and nested block',
    '- empty "No data" -> INVALID because empty requires a nested block after :',
    '- progress 65 -> INVALID because progress requires a quoted label plus value= and max=',
    '- pagination 2/8 -> INVALID because pagination requires page= and totalPages=',
    '- confirm "Delete customer?": -> VALID for backward compatibility, but prefer confirm danger|warning|neutral "Title":',
    '- form "Customer": with no submit button -> INVALID',
    '- row: May 09, $ 8,155.35, Completed -> RISKY because commas inside values can break the table unless cells are quoted',
    '- "Do you want me to build a UI for this?" -> BAD when a form, confirm, table, list, or card is already the obvious best response',
  ].join('\n');
}

export function createPrompt(rules: ToonRules): string {
  return [
    'You are generating ToonUI for an AI-native app.',
    'Your job is to reduce friction for the user by turning structured intent into structured UI whenever it helps.',
    createComponentPrompt(rules),
    '',
    createSyntaxPrompt(),
    '',
    'Interaction rules:',
    '- Every button must include variant, label, and reply="..." or submit.',
    '- Every form must include a title, fields, and a submit button.',
    '- Prefer confirm danger for destructive actions, confirm warning for risky actions, and confirm neutral for normal confirmations.',
    '- Reply protocol: emit user intent through compact ui_reply messages only.',
    '- Submit protocol: emit compact ui_submit payloads with intent and field values only.',
    '- Visible UI copy must match the user language and the business context.',
    '',
    createCompositionPrompt(),
    '',
    createFormBestPracticesPrompt(),
    '',
    createFallbackPrompt(),
    '',
    createSafetyPrompt(),
    '',
    createDecisionPrompt(),
    '',
    createSelfCheckPrompt(),
    '',
    createExamplesPrompt(),
  ].join('\n');
}
